version: '3'
services:
  nginx:
    build: 
        context: AngularTest
        dockerfile: Dockerfile
    ports:
        - "80:80"
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "test"
    volumes:
        - memory:/var/lib/postgresql/data/
  net:
    build:
        context: .
        dockerfile: src/main/docker/Dockerfile.native
    depends_on:
        - db
    ports:
        - "8080:5432"
    environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "test"
volumes: 
    memory:
