version: '3'
services:
  nginx:
    build: 
        context: AngularTest
        dockerfile: Dockerfile
    ports:
        - "80:80"
    networks:
        - front-tier
        - back-tier
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "test"
    ports:
        - target: "5432"
          publicshed: "127.0.0.0:5432"
          protocol: tcp
          mode: host
    volumes:
        - memory:/var/lib/postgresql/data/
    networks:
        - back-tier
  net:
    build:
        context: .
        dockerfile: src/main/docker/Dockerfile.native
    depends_on:
        - db
    environment:
        POSTGRES_USER: "test"
        POSTGRES_PASSWORD: "test"
        POSTGRES_DB: "test"
    networks:
        - back-tier
    ports:
        - "8080:8080"
volumes: 
    memory:
networks:
    front-tier:
    back-tier:
